name: setup ssh
description: starts an ssh agent and loads an ssh key using bash

inputs:
  ssh-private-key:
    description: the ssh private key to load
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        eval $(ssh-agent -s)
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
        cat << 'EOF' > /tmp/ci_key
        ${{ inputs.ssh-private-key }}
        EOF
        chmod 600 /tmp/ci_key
        ssh-add /tmp/ci_key
        rm /tmp/ci_key
