name: nixos ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  flake-check:
    name: evaluate flake
    runs-on: native
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: run nix flake check
        run: nix flake check

  get-hosts:
    name: detect flake hosts
    runs-on: native
    needs: flake-check
    outputs:
      hosts: ${{ steps.set-hosts.outputs.hosts }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: detect flake hosts
        id: set-hosts
        run: |
          HOSTS=$(nix eval .#nixosConfigurations --apply builtins.attrNames --json)
          echo "hosts=$HOSTS" >> "$FORGEJO_OUTPUT"

  build-hosts:
    name: build nixos (${{ matrix.host }})
    runs-on: native
    needs: get-hosts
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJson(needs.get-hosts.outputs.hosts) }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: build ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  ci-succes:
    name: all checks passed
    runs-on: native
    needs:
      - flake-check
      - build-hosts
    steps:
      - name: verify success
        run: echo "everything successfully built!"
