# Mod key
$mainMod = SUPER

# Programs
$terminal = kitty
$browser = librewolf
$launcher = rofi -show drun
$torrent = qbittorrent
$discord = Discord

# Cursor
$cursorTheme = Bibata-Modern-Ice
$cursorSize = 24
