# Make discord start in special workspace
windowrule = match:initial_class ^(discord(-.*)?)$, workspace special:magic silent

# Make browser be workspace 2
windowrule = match:initial_class ^($browser.*)$, workspace 2 silent

# Quickshell Blur
layerrule = match:namespace quickshell, blur on
